# Generated by Django 4.2 on 2024-05-21 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Upvote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "essay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="index.content"
                    ),
                ),
                (
                    "people",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="index.user"
                    ),
                ),
            ],
        ),
    ]
